### ISSUE TITLE
Containerizaion

### ISSUE THREAD

**Issue by fiftydotov** [mossieur/steamfriends.info#2]
Hello i tried to dockerrized repo but i dont get how.

First i try to build image

```
FROM php:8-apache-bookworm

RUN apt-get update && apt-get install -y git unzip \
    && docker-php-ext-install mysqli pdo pdo_mysql \
    && a2enmod rewrite

ENV API_KEY="XXXXXXXXXXXXXXXXXXXXX"
ENV DB_HOST="steamfriends"
ENV DB_USER="user"
ENV DB_PASSWORD="123qweASD!@#"
ENV DB_NAME="database"
ENV ADMINS="765XXXXXXXXXXXXXX"

WORKDIR /var/www/html

RUN git clone https://github.com/mossieur/steamfriends.info.git . \
    && chown -R www-data:www-data /var/www/html

COPY ./configure.sh /usr/local/bin/configure.sh
RUN chmod +x /usr/local/bin/configure.sh

RUN rm /var/www/html/index.html
EXPOSE 80

COPY ./000-default.conf /etc/apache2/sites-available/000-default.conf

```

docker compose file
```

version: '3'
services:
  nginx:
    image: nginx-php:homelab
    restart: unless-stopped
    ports:
      - "8080:8080"
    container_name: steamfriends-php-nginx
    networks:
      - steamfriends-net

  steamfriends:
    image: steamfriends:homelab
    restart: unless-stopped
    container_name: steamfriends
    networks:
      - steamfriends-net

networks:
  steamfriends-net:
    driver: bridge
```

configure.sh 

```
#!/bin/sh
sed -i "s/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/$API_KEY/g" /var/www/html/crontab/GetFriendList.php
sed -i "s/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/$API_KEY/g" /var/www/html/include/steamauth.php

sed -i "s/'localhost', 'user', 'password', 'database'/'$DB_HOST', '$DB_USER', '$DB_PASSWORD', '$DB_NAME'/g" /var/www/html/crontab/GetFriendList.php
sed -i "s/'localhost', 'user', 'password', 'database'/'$DB_HOST', '$DB_USER', '$DB_PASSWORD', '$DB_NAME'/g" /var/www/html/include/config.php

sed -i "s/'765XXXXXXXXXXXXX'/$ADMINS/g" /var/www/html/include/config.php

```

When i connected to nginx reverse container and make 

 curl steamfriends:80
 
```
 <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://steamfriends/">here</a>.</p>
<hr>
<address>Apache/2.4.57 (Debian) Server at steamfriends Port 80</address>
</body></html>

```

I dont how start it on docker, some advice?
